name: Hellow World
on: workflow_dispatch

jobs:
  hellow-job:
    strategy:
      matrix:
        os: [ubuntu-latest , ubuntu-22.04]
        images: ["test 01", "test01"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Echo text     
      run: echo "Hello, world!"  ${{ matrix.images }}