name: Hellow World
on: workflow_dispatch

jobs:
  hellow-job:
    runs-on: ubuntu-latest
    steps:
    - name: Echo text     
      run: echo "Hello, world!" 

  test-job:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
    - name:  test
      run: sleep 10000s        